adminebbs/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from.import views


app_name = 'adminebbs'
urlpatterns = [
    path('dashboard/',views.admindash,name='dashboard'),
    path('adminuser/', views.adminuser, name='adminuser'),
    path('adminuserblock/<int:user_id>/',views.user_block,name='user_block'),
    path('adminuserunblock/<int:user_id>/',views.user_unblock,name='user_unblock'),
    path('admincategory/',views.admincategory,name='categorymanagement'),
    path('addcategory/',views.addcategory,name='addcategory'),
    path('editcategory/',views.editcategory,name='editcategory'),
    path('listunlist/',views.categorylist,name='listunlist'),
    path('unlistlist/',views.productlist,name='unlistlist'),
    path('adminproduct/',views.adminproduct,name='productmanagement'),
    path('productedit/<int:product_id>/',views.editproduct,name='editproduct'),
    path('productadd/',views.addproduct,name='addproduct'),
    path('removeimage/<int:image_id>/',views.removeimage,name='removeimage'),
    path('adminorder/',views.adminorder,name='adminorder'),
    path('adminorderdetails/<int:order_id>/',views.adminorderdetails,name='adminorderdetails'),
    path('orderstatus/<int:order_id>/', views.orderstatus, name='orderstatus'),
    path('admincoupon/', views.admincoupon, name='admincoupon'),
    path('couponadd/', views.couponadd, name='couponadd'),
    path('couponedit/<int:coupon_id>/', views.couponedit, name='couponedit'),
    path('couponremove/<int:coupon_id>/', views.couponremove, name='couponremove'),
    path('get_coupons/', views.get_coupons, name='get_coupons'),
    path('salesreport/', views.salesreport, name='salesreport'),
    path('generate_pdf/', views.generate_pdf, name='generate_pdf'),
    path('generate_excel/', views.generate_excel, name='generate_excel'),
    path('addoffer/',views.addoffer,name='addoffer')














    

     

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ebbsproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('registrationebbs.urls', namespace='r')),
    path('',include('homebbs.urls', namespace='u')),
    path('',include('adminebbs.urls', namespace='a')),
    path('paypal/',include('paypal.standard.ipn.urls')),
]

homebbs/urls.py
from django.urls import path
from.import views



app_name = 'homebbs'
urlpatterns = [
    path('', views.homepage, name='home'),
    path('shop/',views.shoppage,name='shop'),
    path('itempage/<int:product_id>/',views.itempage,name='item'),
    path('addcart/<int:pk>/',views.addtocart,name='addcart'),
    path('cart/',views.cartpage,name='cart'),
    path('checkout/',views.checkoutpage,name='checkout'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('addwishlist/<int:pk>/',views.addwishlist,name='addwishlist'),
    path('removefromwishlist/<int:pk>/',views.removefromwishlist,name='wishlistremove'),
    path('wishaddcart/<int:pk>/',views.wishaddcart,name='wishaddcart'),
    path('checkaddress/',views.checkaddress,name='checkaddress'),
    path('profile/',views.userprofile,name='profile'),
    path('editprofile/',views.editprofile,name='editprofile'),
    path('decrement/<int:id>/',views.decrement_count,name='decrement'),
    path('increment/<int:id>/',views.increment_count,name='increment'),
    path('remove/<int:id>/',views.removefromcart,name='remove'),
    path('addaddress/',views.address,name='addaddress'),    
    path('editaddress/<int:add_id>/',views.editaddress,name='editaddress'),
    path('addremove/<int:add_id>/',views.addressremove,name='addremove'),
    path('error/',views.errorpage,name='error'),
    path('orderconfirm/',views.order_confirm,name='orderconfirm'),
    path('changepassword/',views.changepassword,name='changepassword'),
    path('orderlist/',views.orderlist,name='orderlist'),
    path('orderdetails/<int:order_id>/',views.orderdetails,name='orderdetails'),
    path('cancelorder/<int:order_id>/',views.cancelorder,name='cancelorder'),
    path('returnorder/<int:order_id>/',views.returnorder,name='returnorder'),
    path('wallet/',views.wallet,name='wallet'),
    path('wallethistory/',views.wallethistory,name='wallethistory'),
    path('generate_invoice/<int:order_id>/',views.generate_invoice,name='generate_invoice'),
    path('gallery/',views.gallery,name='gallery'),
    path('razor_success/', views.razor_success, name="razor_success"),








    # path('addtocatshop/<int:prod_id>/',views.addtocartshop,name='addtocartshop'),










]

registrationebbs/urls.py
from django.urls import path
from.import views
from .views import logoutuser


app_name = 'registrationebbs'
urlpatterns = [
    path('login/',views.loginpage,name='login'),
    path('signup/',views.signupage,name='signup'),
    path('logout/',views.logoutuser,name='logout'),
    path('otppage/',views.signupotp,name='otppage'),
    path('adminlogin/',views.adminlogin,name='adminlogin'),
    path('logoutuser/',views.logoutuser,name='logoutuser'),

    # path('forgetpass/',views.forpass,name='forgetpass'),

    

] 

templates/adminlogin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

    <style>
        body {
            background-color: #D9D9D9;


        }

        .btn {
            width: 100%;
        }


        .btn2 {
            margin-top: 20px;
        }

        .form-container {
            padding: 30px;
            background-color: #b8b8b8;
            border-radius: 3px 80px 3px 80px;
        }

        .col-md-12,
        .col-lg-6,
        .col-xl-4 {
            text-align: center;
        }

        .login-heading {
            font-family: 'Inria Serif', serif;
            font-size: 2rem;

        }

        .form-control {
            font-size: 1.2rem;
            padding: 3px 7  px;

        }
        .h4{
            font-family: 'Inria Serif', serif;

        }

        .btn-login{
            padding: 2px 13px;
            background-color: black;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            font-family: 'Inria Serif', serif;

        }
      
    </style>

</head>
<body>
    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex align-items-center justify-content-center h-100">
                <div class="col-md- col-lg-5 col-xl-5 offset-xl-1">
                    
                    <div class="container form-container">
                        <div class="container form-container d-flex flex-column align-items-center"
                            style="height: 100px;">
                            <h4 class="h4">AdminLogin Alams</h4>
                        </div>

                        <form method="POST" action="{% url 'r:adminlogin' %}">
                            {% csrf_token %}
                            <div class="mb-4" style=" font-family: 'Inria Serif', serif;">
                                <label for="uname" class="form-label">Username</label>
                                <input type="text" id="uname" name="email" class="form-control" required />
                            </div>
                        
                            <div class="mb-4" style=" font-family: 'Inria Serif', serif;">
                                <label for="psw" class="form-label">Password</label>
                                <input type="password" id="psw" name="password" class="form-control" required />
                            </div>
                            
                            <button type="submit" class="btn-login">Login</button>
                            <br>
                            {% if error %}
                            <p class="text-danger text-center">{{error}}</p>
                            {% endif %}
                            
                        </form>
                        
                    </div>
                </div>

                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
            </div>
        </div>
        </div>
    </section>
</body>

</html>

templates/adminproduct.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body {
            font-family: Fondamento;
            margin: 0;
            padding: 0;

        }

        .sidebar {
            width: 250px;
            height: 100%;
            background-color: #ffffff;
            color: #333;
            position: fixed;
            top: 0;
            left: 0;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            align-items: center;
            padding-top: 20px;
            border-right: 5px solid #000000;
        }

        .main-content {
            margin-left: 250px;
            padding: 20px;
        }


        .search-container button {
            background-color: #000000;
            color: white;
            border: none;
            padding: 5px 40px;
            border-radius: 5px;
            cursor: pointer;
        }

        /* Style for the sidebar links */
        .sidebar ul {
            list-style-type: none;
            padding: 0;
            text-align: left;
            /* Align the text to the left */
            margin-top: 20px;
            /* Adjust the top margin */
        }

        .sidebar ul li {
            padding: 10px 0;
        }

        .sidebar ul li a {
            display: flex;
            /* Align icon and text horizontally */
            align-items: center;
            padding: 10px;
            color: #000000;
            font-weight: bold;
            text-decoration: none;
        }

        .sidebar ul li a:hover {
            background-color: #D9D9D9;
            /* Light background color on hover */
        }

        /* Additional spacing between icon and text */
        .sidebar ul li a span {
            margin-right: 10px;

        }



        .unbutton {

            background-color: #f11414;
            color: white;
            font-family: 'Inria Serif', serif;
            border: none;
            padding: 5px 7px;
            border-radius: 5px;
            cursor: pointer;
        }



        .libutton {

            background-color: #5ef11a;
            font-family: 'Inria Serif', serif;
            color: white;
            border: none;
            padding: 5px 7px;
            border-radius: 5px;
            cursor: pointer;
        }


        .addbutton {
            background-color: #2e8993;
            font-family: 'Inria Serif', serif;
            color: white;
            border: none;
            padding: 5px 8px;
            border-radius: 5px;
            cursor: pointer;
        }

        .editbutton {
            background-color: #2e8993;
            font-family: 'Inria Serif', serif;
            color: white;
            border: none;
            padding: 5px 7px;
            border-radius: 5px;
            cursor: pointer;
        }


        /* Style for the dashboard cards */
        .card {
            background-color: #fff;
            color: #000000;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        /* Adjust table styles */
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }


        .pagination {
            display: flex;
            justify-content: center;
            margin-top: 40px;
            margin-bottom: 40px;
        }

        .pagination .page-link {
            color: black;
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            padding: 2px 7px;
            margin: 0 3px;
            text-decoration: none;
            border-radius: 7px;
            margin-bottom: 5%;
            cursor: pointer;
        }

        .pagination .page-link:hover {
            background-color: #f8f9fa;
        }

        .pagination .page-item.active .page-link {
            background-color: #040d16;
            color: #ffffff;
            border-color: #000000;
        }

        .pagination .page-item.disabled .page-link {
            color: #6c757d;
            pointer-events: none;
            background-color: #ffffff;
            border-color: #dee2e6;
        }

        .pagination .page-item:first-child .page-link,
        .pagination .page-item:last-child .page-link {
            border-radius: 8px;
        }
    </style>
</head>

<body>
    <div class="sidebar">
        <h4
            style="text-align: center; text-decoration: underline; text-underline-offset: 0.25em; font-family: Fondamento;">
            A L A M S</h4>
        <ul>
            <li><a href="{% url 'a:dashboard' %}"><span class="bi bi-bar-chart"></span> Dashboard</a></li>
            <li><a href="{% url 'a:productmanagement' %}"><span class="bi bi-box"></span> Products</a></li>
            <li><a href="{% url 'a:adminuser' %}"><span class="bi bi-person"></span> Users</a></li>
            <li><a href="{% url 'a:adminorder' %}"><span class="bi bi-cart"></span> Orders</a></li>
            <li><a href="{% url 'a:categorymanagement' %}"><span class="bi bi-folder"></span> Category</a></li>
            <li><a href="{% url 'a:admincoupon' %}"><span class="bi bi-ticket"></span> Coupons</a></li>
            <li><a href="{% url 'a:salesreport' %}"><span class="bi bi-graph-up"></span> Sales Report</a></li>
            <li><a href="{% url 'r:logout' %}"><span class="bi bi-box-arrow-right"></span> Logout</a></li>
        </ul>
    </div>

    <div class="main-content" style="justify-content: space-between;">
        <h5>Product Management</h5>
        <div style="display: flex; justify-content: space-between;">
            <!-- <div class="search-container">
                <input type="text" name="search" placeholder="tap here !">
                <button type="submit"><span class="bi bi-search"></span></button>
            </div> -->
            <a href="{% url 'a:addproduct' %}"><button class="addbutton">Add Products</button> </a>
            <a href="{% url 'a:addoffer' %}"><button class="addbutton">Add Offers</button> </a>
        </div>
        <br>
    {% if products %}
        <table>
            <thead>
                <tr>
                    <th>sl|no</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Price</th>
                    <th>Stock</th>
                    <th>Image</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ product.name }}</td>
                    <td>{{ product.category.name }}</td>
                    <td>{{ product.price }}</td>
                    <td>{{ product.stock }}</td>

                    {% if product.images %}
                    <td><img src="{{ product.images.first.image.url }}" alt="ProductImage" style="width: 50px;"></td>
                    {% else %}
                    <td>
                        <h6>No products were added !!!</h6>
                    </td>
                    {% endif %}

                    <td>
                        <a href="{% url 'a:editproduct' product.id %}"><button class="editbutton">Edit</button></a>
                        {% if product.listt %}
                        <a href="{% url 'a:unlistlist' %}?prod_id={{product.id}}"><button
                                class="libutton">List</button></a>
                        {% else %}
                        <a href="{% url 'a:unlistlist' %}?prod_id={{product.id}}"><button
                                class="unbutton">unlist</button></a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>


        </table>
    </div>

    <!-- Pagination -->
    <div class="pagination">
        <!-- Previous link -->
        {% if products.has_previous %}
        <span class="page-item">
            <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
        </span>
        {% else %}
        <span class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </span>
        {% endif %}
    
        <!-- Page numbers -->
        {% if products.number == 2 %}
            {% for num in products.paginator.page_range %}
            <span class="page-item {% if products.number == num %}active{% endif %}">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
            </span>
            {% endfor %}
        {% else %}
            <span class="page-item {% if products.number == 1 %}active{% endif %}">
                <a class="page-link" href="?page=1">1</a>
            </span>
            <span class="page-item {% if products.number == 2 %}active{% endif %}">
                <a class="page-link" href="?page=2">2</a>
            </span>
        {% endif %}
    
        <!-- Next link -->
        {% if products.has_next %}
        <span class="page-item">
            <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
        </span>
        {% else %}
        <span class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </span>
        {% endif %}
    </div>
    {% else %}
    <h5 style="text-align: center;">Currently no products added.</h5>
    {% endif %}
    
</body>

</html>

templates/orderlist.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>orders</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        .navbar {
            background-color: #000000;
        }

        .navbar-brand {
            font-family: 'Inria Serif', serif;
            color: #ffffff;
        }

        .navbar-nav {
            margin-left: auto;
            display: flex;
            align-items: center;
        }

        .navbar-nav .nav-link {
            color: #ffffff;
            margin: 0 15px;
        }

        .navbar-nav .nav-link:hover {
            color: #ffffff;
        }

        .navbar-brand {
            flex: 1;
            justify-content: center;
        }

        .nav-item {
            flex: -1;
            justify-content: flex-end;
        }

        .navbar-nav {

            flex: 1;
            justify-content: center;
        }

        .navbar-nav .nav-link#shop,
        .navbar-nav .nav-link#brand {

            color: #ffffff;
            font-family: 'Inria Serif', serif;
        }

        .bi {
            color: #fffcfc;
        }

        .custom-heading {
            font-family: 'Inria Serif', serif;
            margin-top: 20px;
            letter-spacing: 10px;
        }

        .paragraph {
            font-family: 'Inria Serif', serif;
            margin-left: 20%;
            margin-right: 20%;
            margin-top: 4%;
            letter-spacing: 4px;

        }

        .site-footer {
            display: flex;
            font-family: 'Inria Serif', serif;
            flex-wrap: wrap;
            justify-content: space-between;
            padding: 1rem 0;
            background-color: #ffffff;
            margin-top: 13%;
        }

        .footer-underline {
            border: none;
            border-top: 3px solid #050829;
            width: 100%;
        }

        .footer-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
            width: 100%;
            padding: 1rem;
        }

        .abalone-text {
            margin-right: auto;
        }

        .copyright {
            margin: 0 auto;
        }

        .right-section {
            display: flex;
            justify-content: flex-end;
            align-items: center;
            margin-left: auto;
        }

        .right-section a img {
            margin-left: 1rem;
            height: 24px;
        }

        .right-content .icon i {
            color: #000 !important;
            margin-right: 40px;

        }

        @media (max-width: 768px) {
            .footer-content {
                flex-direction: column;
            }
        }

        
        .cancel-btn {
            padding: 1px 7px;
            margin-right: 10px;
            border: none;
            background-color: #a787ed;
            color: #fff;
            cursor: pointer;
            border-radius: 5px;
        }

        .return-btn {
            padding: 1px 5px;
            margin-right: 10px;
            border: none;
            background-color: rgb(192, 20, 20);
            color: #fff;
            cursor: pointer;
            border-radius: 5px;

        }
        .invoice-btn{
            padding: 1px 6px;
            margin-right: 2px;
            border: none;
            background-color: rgb(0, 224, 150);
            color: #fff;
            cursor: pointer;
            border-radius: 5px;
        }

        .heading {
            text-align: center;
            font-family: 'Inria Serif', serif;
            margin-top: 30px;
            margin-bottom: 30px;
        }

        .order-table {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
            font-family: 'Inria Serif', serif;

        }

        .order-row {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }

        .order-item {
            width: 100%;
            border: 1px solid #e0dddd;
            padding: 20px;
            display: flex;
            justify-content: space-between;
        }

        .image-container {
            max-width: 60px;
            width: 100%;
            height: auto;

        }


        .image-container img {
            max-width: 100%;
            height: auto;
            border-radius: 15px;

        }
        .details {
            margin-top: 10px;
        }

        .date,
        .price,
        .status {
            margin-bottom: 5px;
        }

       
        .darker-icon {
            color: black;
            cursor: pointer;
            filter: brightness(0.9);

        }

        .pagination {
            display: flex;
            justify-content: center;
            font-family: 'Inria Serif', serif;
            margin-top: 30%;
            margin-bottom: 10px;
        }

        .pagination .page-link {
            color: rgb(255, 255, 255);
            background-color: #080505;
            border: 1px solid #000000;
            padding: 2px 7px;
            margin: 0 3px;
            text-decoration: none;
            border-radius: 9px;
            cursor: pointer;
        }

        .pagination .page-link:hover {
            background-color: #f8f9fa;
        }

        .pagination .page-item.active .page-link {
            background-color: #040d16;
            color: #ffffff;
            border-color: #000000;
        }

        .pagination .page-item.disabled .page-link {
            color: #7f8285;
            pointer-events: none;
            background-color: #ffffff;
            border-color: #dee2e6;
        }

        .pagination .page-item:first-child .page-link,
        .pagination .page-item:last-child .page-link {
            border-radius: 10px;
        }

        .modal-content {
        width: 300px; 
    }

    .modal {
        position: fixed;
        top: 50%;
        left: 50%; 
        transform: translate(-50%, -50%);
    }

    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'u:home' %}">AlamS</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">

                    <li class="nav-item">
                        <a id="brand" class="nav-link" href="{% url 'u:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a id="brand" class="nav-link" href="{% url 'u:shop' %}">Shop</a>
                    </li>


                    <li class="nav-item">
                        <a id="brand" class="nav-link" href="{% url 'u:gallery' %}">Gallery</a>
                    </li>
                </ul>
                <ul class="navbar-nav" style="display: flex; text-align: end;">

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'u:profile' %}"><i class="bi bi-person"></i></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'u:cart' %}"><i class="bi bi-cart"></i></a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href=""><i class="bi bi-heart"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <h5 class="heading">My Orders</h5>
        <div class="order-table">
            <div class="order-row">
            {% for order in orders  %}
                <div class="order-item">
                    <div class="id">Order ID : {{order.order_id}}</div>
                    <div class="date">Delivery Expected: {{ order.delivery_date_plus_7_days|date:"F j, Y" }}</div>
                    <div class="price">₹ {{order.total_orderprice}}</div>
                    <div class="status">
                        {% if order.status == 'Cancelled' %}
                            Cancelled
                        {% elif order.status == 'Delivered' %}
                            Delivered
                        {% else %}
                            {{order.status}}
                        {% endif %}
                        </div>
                    <div class="actions">
                        {% if order.status == 'Ordered' %}
                        <a href="{% url 'u:cancelorder' order.id %}"><button class="cancel-btn">Cancel Order</button></a>
                        {% elif order.status == 'Cancelled' %}
                         Order Cancelled
                        {% elif order.status == 'Delivered' %}
                        <a href="{% url 'u:returnorder' order.id %}" onclick="openReturnModal('{{ order.id }}')">
                            <button class="return-btn">Return Order</button>
                        </a>
                       <a href="{% url 'u:generate_invoice' order.id %}"><button class="invoice-btn">Invoice</button></a>
                        {% elif order.status == 'Returned' %}
                        Return approved
                        {% endif %}
                        <a href="{% url 'u:orderdetails' order.id %}"><span class="bi bi-chevron-right darker-icon"></span></a>
                    </div>
                </div>
            {% endfor %}
            
            </div>
        </div>
    </div>


     <!-- Pagination -->
     <div class="pagination">
        {% if products.has_previous %}
        <span class="page-item">
            <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
        </span>
        {% else %}
        <span class="page-item disabled">
            <a class="page-link" href="#">Previous</a>
        </span>
        {% endif %}

        <!-- Page numbers -->
        {% if products.number == 2 %}
        {% for num in products.paginator.page_range %}
        <span class="page-item {% if products.number == num %}active{% endif %}">
            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </span>
        {% endfor %}
        {% else %}
        <span class="page-item {% if products.number == 1 %}active{% endif %}">
            <a class="page-link" href="?page=1">1</a>
        </span>
        <span class="page-item {% if products.number == 2 %}active{% endif %}">
            <a class="page-link" href="?page=2">2</a>
        </span>
        {% endif %}

        <!-- Next link -->
        {% if products.has_next %}
        <span class="page-item">
            <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
        </span>
        {% else %}
        <span class="page-item disabled">
            <a class="page-link" href="#">Next</a>
        </span>
        {% endif %}
    </div>

    <!-- Footer -->
    <footer class="site-footer">
        <div class="footer-content">
            <div class="left-section">
                <span class="abalone-text">Abalone</span>
            </div>
            <div class="center-section">
                <span class="copyright">copyright©Ebbs|2024</span>
            </div>
            <div class="right-content">
                <a href="#" class="icon instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="icon twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="icon linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"
            integrity="sha512-K2h7EtEaLljw8lIbVmSdWYU2PNT9dUd4ft5q3wug+y05ZgSagZBmUOOQFBmtJYWnSKgpHnCg0SX27TzOvtarbg=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>